FROM python:3.10-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PORT=8000
ENV ALLOW_STALE_CACHE=true

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN python train.py

EXPOSE 8000

CMD ["python", "api.py"]
